# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '玩转西邮' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 玩转西邮
  use_frameworks!
  inhibit_all_warnings!
    pod 'ReactiveObjC'
    pod 'AFNetworking'
    pod 'SVProgressHUD'
    pod 'YYKit'
    pod 'Masonry'

  target '玩转西邮Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '玩转西邮UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
